/*****************************************************************/
/*              SAMPLE PROGRAM HEADER FILE (SAMPLE.H)            */
/*****************************************************************/

#define WND_MainWnd         100
#define AB_File             110
#define   AB_New            111
#define   AB_Open           112
#define   AB_Save           113
#define   AB_Saveas         114
#define   AB_Exit           115
#define AB_Help             190
#define   AB_Hhelp          191
#define   AB_Xhelp          192
#define   AB_Khelp          193
#define   AB_Ihelp          194
#define   AB_About          195

#define DLG_About           900
